version: "3.9"

services:
  app-nginx:
    build:
      context: ./app/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - app-php-fpm
    ports:
      - "8080:80"

  app-php-fpm:
    build:
      context: ./app/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - app-postgres

  app-php-cli:
    build:
      context: ./app/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache
    tty: true
    depends_on:
      - app-postgres

  app-postgres:
    image: postgres:16.1-alpine
    volumes:
      - app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8801:8080"

volumes:
  app-postgres:
  composer: